services:
  - type: web
    name: snooker-alert-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python snooker_alert_bot.py
    pythonVersion: 3.11.8
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: telegram-token-secret-name
